- name: Variable
  hosts: all
  vars:
    URL: vars.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: Print URL from tasks
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.example.com

- name: Variable from files
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Variable from Inv
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Facts
  hosts: all
  vars:
    ansible_distribution: TEST
  tasks:
    - name: Print Fact
      ansible.builtin.debug:
        msg: OS Distribution = {{ ansible_distribution }}
## Facts can be overwritten by the vars from user, Usually it is not a good practice.

- name: Register a Variable
  hosts: all
  tasks:
    - name: Uptime commands
      ansible.builtin.shell: uptime
      register: OUT

    - name: Print OUT
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"

