- name: Variable
  hosts: all
  vars:
    URL: vars.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: Print URL from tasks
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.example.com

- name: Variable from files
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Variable from Inv
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

