- name: Variable
  hosts: all
  vars:
    URL: vars.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: Print URL from tasks
      ansible.builtin.debug:
        msg: URL = {{ URL1 }}
      vars:
        URL: tasks.example.com
