- name: test
  hosts: localhost
  tasks:
    - name: Include a role
      loop:
        - apple
        - banana
      include_role:
        name: demo

#    - name: Block
#      loop:
#        - apple
#        - banana
#      block:
#        - name: print1
#          debug:
#            msg: Name = {{item}}

